

data_set:
  name: imdb_reviews
  schema_file_path: dataset_schema.yaml

preprocessing:
  vocab_size: 1000


train_config: 
  buffer_size: 10000
  batch_size: 64


training_pipeline_config:
  artifact_dir: aritifacts
  

