

data_set:
  name: imdb_reviews
  schema_file_path: dataset_schema.yaml
  buffer_size: 10000
  batch_size: 64


preprocessing:
  vocab_size: 1000


train_config: 



training_pipeline_config:
  artifact_dir: artifacts
  

